name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_AUTH_SERVER: http://localhost
      NEXT_PUBLIC_SIGNALING_SERVER: ws://localhost
    strategy:
      matrix:
        node: ["14.x", "16.x"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
